
from PIL import Image, ImageFilter, ImageChops
from pathlib import Path
import argparse
import re

# Edit these colors to whatever exact HTML colors you want.
# _1 = resized original white icon
# _2 through _6 = recolored icons that preserve dark details/shading
# _7 = God tier, generated by the black/gold workflow
TIER_COLORS = [
    "#68F968",  # _2
    "#38A6F6",  # _3
    "#852EC8",  # _4
    "#D6D162",  # _5
    "#FF3646",  # _6
]

OUTPUT_SIZE = 160

# God tier settings. This keeps the previous black/gold style,
# but now preserves the original dark internal details as gold.
GOD_SHRINK = 0
GOD_BLUR = 3.0
GOD_GOLD = "#FFD23C"
GOD_BLACK = "#000000"


def hex_to_rgb(hex_color):
    hex_color = hex_color.strip().lstrip("#")

    if len(hex_color) != 6:
        raise ValueError(f"Invalid color: {hex_color}. Use format like #FFD23C")

    return tuple(int(hex_color[i:i + 2], 16) for i in (0, 2, 4))


def hex_to_rgba(hex_color):
    return hex_to_rgb(hex_color) + (255,)


def rename_tier(input_path, tier_number):
    """
    Changes a filename ending in _1, _2, etc. to the requested tier.
    Example: ui_buff_duration_icon_1.png -> ui_buff_duration_icon_7.png
    """
    new_stem = re.sub(r'_\d+$', f'_{tier_number}', input_path.stem)
    return f"{new_stem}{input_path.suffix}"


def colorize_preserve_shading(image, hex_color):
    """
    Recolors the icon while preserving internal dark details.

    White pixels become the chosen color.
    Gray pixels become darker shades of that color.
    Black pixels stay black.
    Transparency is preserved.
    """
    img = image.convert("RGBA")
    alpha = img.getchannel("A")
    luminance = img.convert("L")

    r, g, b = hex_to_rgb(hex_color)

    red = luminance.point(lambda v: int(v * r / 255))
    green = luminance.point(lambda v: int(v * g / 255))
    blue = luminance.point(lambda v: int(v * b / 255))

    result = Image.merge("RGBA", (red, green, blue, alpha))
    return result


def alpha_tint(image, hex_color):
    """Solid tint using only the image alpha. Used for the God glow."""
    img = image.convert("RGBA")
    alpha = img.getchannel("A")
    solid = Image.new("RGBA", img.size, hex_to_rgba(hex_color))
    solid.putalpha(alpha)
    return solid


def make_god_icon(resized_white):
    """
    Creates the God tier icon:
    - gold blurred glow from the full icon silhouette
    - black icon scaled down by GOD_SHRINK and centered
    - original dark internal details restored as gold on top
    """
    img = resized_white.convert("RGBA")
    width, height = img.size

    # Gold glow/outline from the full icon silhouette
    gold_silhouette = alpha_tint(img, GOD_GOLD)
    glow = gold_silhouette.filter(ImageFilter.GaussianBlur(radius=GOD_BLUR))

    # Main black icon, scaled down
    black_icon = alpha_tint(img, GOD_BLACK)
    scaled_black = black_icon.resize(
        (width - GOD_SHRINK, height - GOD_SHRINK),
        Image.Resampling.LANCZOS
    )

    centered_black = Image.new("RGBA", img.size, (0, 0, 0, 0))
    offset = ((width - scaled_black.width) // 2, (height - scaled_black.height) // 2)
    centered_black.alpha_composite(scaled_black, offset)

    # Gold internal details:
    # original dark pixels become visible gold details.
    original_alpha = img.getchannel("A")
    luminance = img.convert("L")
    inverse_luminance = ImageChops.invert(luminance)

    # Keep detail only where the original icon is opaque/semi-opaque
    detail_alpha = ImageChops.multiply(inverse_luminance, original_alpha)

    gold_details = Image.new("RGBA", img.size, hex_to_rgba(GOD_GOLD))
    gold_details.putalpha(detail_alpha)

    scaled_details = gold_details.resize(
        (width - GOD_SHRINK, height - GOD_SHRINK),
        Image.Resampling.LANCZOS
    )

    centered_details = Image.new("RGBA", img.size, (0, 0, 0, 0))
    centered_details.alpha_composite(scaled_details, offset)

    result = Image.new("RGBA", img.size, (0, 0, 0, 0))
    result.alpha_composite(glow)
    result.alpha_composite(centered_black)
    result.alpha_composite(centered_details)

    return result


def process_icon(input_path, output_dir):
    original = Image.open(input_path).convert("RGBA")

    resized_white = original.resize(
        (OUTPUT_SIZE, OUTPUT_SIZE),
        Image.Resampling.LANCZOS
    )

    # _1: resized original white icon
    out_name = rename_tier(input_path, 1)
    resized_white.save(output_dir / out_name)
    print(f"Saved {out_name}")

    # _2 through _6: recolored versions with preserved dark details
    for tier_number, color in enumerate(TIER_COLORS, start=2):
        recolored = colorize_preserve_shading(resized_white, color)
        out_name = rename_tier(input_path, tier_number)
        recolored.save(output_dir / out_name)
        print(f"Saved {out_name}")

    # _7: God tier
    god_icon = make_god_icon(resized_white)
    out_name = rename_tier(input_path, 7)
    god_icon.save(output_dir / out_name)
    print(f"Saved {out_name}")


def main():
    parser = argparse.ArgumentParser(
        description="Resize white icons to 160x160 and generate tiers _1 through _7."
    )
    parser.add_argument("input", help="Folder containing the source PNG icons, usually ending in _1.png")
    parser.add_argument("output", help="Folder where generated tier icons will be saved")
    args = parser.parse_args()

    input_dir = Path(args.input)
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    png_files = sorted(input_dir.glob("*.png"))

    if not png_files:
        print("No PNG files found in the input folder.")
        return

    for input_path in png_files:
        process_icon(input_path, output_dir)


if __name__ == "__main__":
    main()
